#!/usr/bin/env python3
"""Generate traceable SDD support artifacts from canonical package evidence.

The canonical requirements, design, tasks, testing strategy, decisions, and
machine-readable checkpoints remain authoritative. This script materializes
the four derived review artifacts that must stay synchronized with them:

* CHECKLIST.md
* CROSS_ANALYSIS.md
* VERIFICATION.md
* SOURCE_TRACEABILITY.md

It never invents a source, task, test, approval, or execution result. Missing
or inconsistent evidence is a hard error. Existing hand-authored files are
left untouched; only absent files or files carrying this script's generated
marker are managed.

Passing ``--include-supplements`` additionally materializes three managed
derived projections per package:

* FRD.md  (functional requirements projected from REQ-* records)
* NFRD.md (quality requirements projected from NFR-* records)
* TDD.md  (ordered task/test plan projected from the plan-to-tasks and
  test-coverage checkpoints)

Without the flag, behavior is unchanged from the original four-artifact
workflow. Hand-authored FRD.md/NFRD.md/TDD.md files (files without this
script's generated marker) are never overwritten, even with
``--force-generated``.
"""

from __future__ import annotations

import argparse
import collections
import dataclasses
import hashlib
import json
import pathlib
import re
import sys
from dataclasses import dataclass
from typing import Any

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import sdd_lib  # noqa: E402

ROOT = sdd_lib.repo_root()
CONFIG = sdd_lib.load_config(ROOT)
DEFAULT_SPEC_ROOT = sdd_lib.spec_root(ROOT, CONFIG)
GENERATED_MARKER = (
    "<!-- GENERATED BY .github/scripts/generate-sdd-support-artifacts.py; "
    "DO NOT EDIT DIRECTLY. -->"
)
SUPPORT_ARTIFACTS = (
    "CHECKLIST.md",
    "CROSS_ANALYSIS.md",
    "VERIFICATION.md",
    "SOURCE_TRACEABILITY.md",
)
SUPPLEMENT_ARTIFACTS = (
    "FRD.md",
    "NFRD.md",
    "TDD.md",
)
CHECKPOINT_ARTIFACTS = (
    "checkpoints/spec-to-plan.yaml",
    "checkpoints/plan-to-tasks.yaml",
    "checkpoints/test-coverage.yaml",
)
TASK_SOURCE_BLOCK = re.compile(
    r"^-\s+\[[ xX]\]\s+\*\*(?P<id>T\d{3})\b(?P<body>.*?)"
    r"(?=^-\s+\[[ xX]\]\s+\*\*T\d{3}\b|^#{1,6}\s|\Z)",
    re.MULTILINE | re.DOTALL,
)
CORE_ARTIFACTS = (
    "SPECIFICATION.md",
    "ANALYSIS.md",
    "DESIGN.md",
    "TASKS.md",
    "TESTING.md",
    "DECISIONS.md",
)
PACKAGE = re.compile(r"^\d{3}-[a-z0-9-]+$")
FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
REQUIREMENT_BLOCK = re.compile(
    r"^-\s+\*\*(?P<id>(?:REQ|NFR)-\d{3}):\*\*\s+"
    r"(?P<statement>.*?)(?=^-\s+\*\*(?:REQ|NFR)-\d{3}:\*\*|\Z)",
    re.MULTILINE | re.DOTALL,
)
SOURCE_ID = re.compile(r"\bSRC-\d{3}\b")
SOURCE_KEY = re.compile(
    r"^\s*(?:" + "|".join(re.escape(k) for k in CONFIG["sourceKeys"]) + r")\s*:", re.I
)
FIELD = re.compile(
    r"^\s+-\s+(?P<name>Pattern|Priority|Rationale|Acceptance|Verification):"
    r"\s*(?P<value>.+?)\s*$",
    re.MULTILINE,
)
COMBINED_STATUS = re.compile(
    r"^\s+-\s+Priority:\s*(?P<priority>[^.]+)\.\s+"
    r"Source:\s*(?P<source>.+?)\.\s+Status:\s*(?P<status>[^.]+)\.\s*$",
    re.MULTILINE,
)
CATALOG_ROW = re.compile(
    r"^\|\s*(?P<id>(?:REQ|NFR)-\d{3})\s*\|\s*(?P<priority>[^|]+)\|"
    r"\s*(?P<source>[^|]+)\|\s*(?P<acceptance>[^|]+)\|",
    re.MULTILINE,
)
ACCEPTANCE_ROW = re.compile(
    r"^\|\s*(?P<id>AC-[A-Z0-9-]+)\s*\|(?P<body>.+)\|\s*"
    r"(?P<requirement>(?:REQ|NFR)-\d{3})\s*\|",
    re.MULTILINE,
)


class GenerationError(RuntimeError):
    """Raised when authoritative package evidence cannot support generation."""


@dataclass(frozen=True)
class Requirement:
    identifier: str
    statement: str
    priority: str
    sources: tuple[str, ...]
    lifecycle_status: str
    acceptance: str
    verification: str


@dataclass(frozen=True)
class Source:
    identifier: str
    evidence: str
    relevance: str
    confidence: str


@dataclass(frozen=True)
class PackageEvidence:
    path: pathlib.Path
    feature_id: str
    slug: str
    title: str
    implementation_status: str
    requirements: tuple[Requirement, ...]
    sources: tuple[Source, ...]
    spec_to_plan: dict[str, Any]
    plan_to_tasks: dict[str, Any]
    test_coverage: dict[str, Any]
    source_texts: dict[str, str]
    source_hashes: dict[str, str]

    @property
    def generated_on(self) -> str:
        dates = [
            str(document.get("checkpoint", {}).get("generated_on", ""))
            for document in (
                self.spec_to_plan,
                self.plan_to_tasks,
                self.test_coverage,
            )
        ]
        present = sorted(date for date in dates if date)
        return present[-1] if present else "not-recorded"


def load_yaml(path: pathlib.Path) -> dict[str, Any]:
    try:
        document = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as error:
        raise GenerationError(f"{path}: cannot load YAML: {error}") from error
    if not isinstance(document, dict):
        raise GenerationError(f"{path}: expected a non-empty YAML mapping")
    return document


def parse_frontmatter(text: str, path: pathlib.Path) -> dict[str, Any]:
    match = FRONTMATTER.match(text)
    if match is None:
        raise GenerationError(f"{path}: YAML frontmatter is required")
    try:
        document = yaml.safe_load(match.group(1))
    except yaml.YAMLError as error:
        raise GenerationError(f"{path}: invalid YAML frontmatter: {error}") from error
    if not isinstance(document, dict):
        raise GenerationError(f"{path}: frontmatter must be a mapping")
    return document


def clean_cell(value: Any) -> str:
    return " ".join(str(value).split()).replace("|", "\\|")


def code_cell(value: Any, *, placeholder: str = "not-recorded") -> str:
    """Render a technical evidence surface (a path) as an inline code span.

    Evidence paths are literal identifiers, so they must keep their exact
    casing while remaining prose-lint safe in a generated table cell. The
    placeholder is emitted as plain text because it is not a path.
    """

    cleaned = clean_cell(value)
    if not cleaned or cleaned == placeholder or "`" in cleaned:
        return cleaned
    return f"`{cleaned}`"


def requirement_statement(raw: str) -> str:
    lines: list[str] = []
    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped or FIELD.match(line) or COMBINED_STATUS.match(line) or SOURCE_KEY.match(line):
            break
        if lines and not line.startswith((" ", "\t")):
            break
        lines.append(stripped)
    return clean_cell(" ".join(lines))


def lifecycle_status(document_status: Any) -> str:
    normalized = clean_cell(document_status).lower()
    if normalized in {"approved", "implemented", "verified"}:
        return normalized
    if normalized in {"review", "ready for review", "ready-for-review"}:
        return "ready for review"
    return "proposed"


def parse_requirements(
    text: str,
    path: pathlib.Path,
    *,
    default_status: str,
    test_coverage: dict[str, Any],
) -> tuple[Requirement, ...]:
    catalog = {
        match.group("id"): {
            "priority": clean_cell(match.group("priority")),
            "source": clean_cell(match.group("source")).strip("`"),
            "acceptance": clean_cell(match.group("acceptance")).strip("`"),
        }
        for match in CATALOG_ROW.finditer(text)
    }
    acceptance_rows: dict[str, str] = {}
    for match in ACCEPTANCE_ROW.finditer(text):
        cells = [
            clean_cell(cell)
            for cell in match.group("body").split("|")
            if clean_cell(cell)
        ]
        acceptance_rows[match.group("id")] = (
            cells[-1] if cells else f"Scenario {match.group('id')}"
        )
    coverage = test_coverage.get("requirements", {})
    if not isinstance(coverage, dict):
        raise GenerationError(
            f"{path.parent / 'checkpoints/test-coverage.yaml'}: "
            "requirements must be a mapping"
        )
    requirements: list[Requirement] = []
    for match in REQUIREMENT_BLOCK.finditer(text):
        block = match.group(0)
        combined = COMBINED_STATUS.search(block)
        fields = {
            field.group("name").lower(): clean_cell(field.group("value"))
            for field in FIELD.finditer(block)
        }
        identifier = match.group("id")
        catalog_entry = catalog.get(identifier)
        if combined is not None:
            priority = clean_cell(combined.group("priority"))
            sources = tuple(
                dict.fromkeys(SOURCE_ID.findall(combined.group("source")))
            )
            status = clean_cell(combined.group("status"))
            acceptance = fields.get("acceptance", "Not recorded")
        elif catalog_entry is not None:
            priority = str(catalog_entry["priority"])
            source_text = str(catalog_entry["source"])
            stable_sources = tuple(dict.fromkeys(SOURCE_ID.findall(source_text)))
            sources = stable_sources or (f"RAW::{source_text}",)
            status = default_status
            acceptance_id = str(catalog_entry["acceptance"])
            acceptance = (
                f"{acceptance_id}: {acceptance_rows[acceptance_id]}"
                if acceptance_id in acceptance_rows
                else f"{acceptance_id} in SPECIFICATION.md"
            )
        else:
            raise GenerationError(
                f"{path}: {identifier} has neither inline metadata nor a "
                "requirement catalog row"
            )
        if not sources:
            raise GenerationError(
                f"{path}: {identifier} has no stable SRC identifier"
            )
        test_mapping = coverage.get(identifier)
        if not isinstance(test_mapping, dict) or not test_mapping.get("tests"):
            raise GenerationError(
                f"{path}: {identifier} has no test-coverage mapping"
            )
        verification = clean_cell(
            ", ".join(str(item) for item in test_mapping["tests"])
        )
        requirements.append(
            Requirement(
                identifier=identifier,
                statement=requirement_statement(match.group("statement")),
                priority=priority,
                sources=sources,
                lifecycle_status=status,
                acceptance=acceptance,
                verification=fields.get("verification", verification),
            )
        )
    if not requirements:
        raise GenerationError(f"{path}: no canonical REQ/NFR blocks found")
    identifiers = [item.identifier for item in requirements]
    duplicates = sorted(
        identifier
        for identifier, count in collections.Counter(identifiers).items()
        if count > 1
    )
    if duplicates:
        raise GenerationError(f"{path}: duplicate requirements: {duplicates}")
    return tuple(requirements)


def parse_explicit_sources(
    texts: tuple[tuple[str, pathlib.Path], ...],
) -> dict[str, Source]:
    sources: dict[str, Source] = {}
    for text, path in texts:
        for line_number, line in enumerate(text.splitlines(), 1):
            if not line.startswith("|"):
                continue
            cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
            if len(cells) < 2 or SOURCE_ID.fullmatch(cells[0]) is None:
                continue
            identifier = cells[0]
            source = Source(
                identifier=identifier,
                evidence=clean_cell(cells[1]),
                relevance=clean_cell(
                    cells[2] if len(cells) >= 3 else "Defined source evidence."
                ),
                confidence=clean_cell(
                    cells[3] if len(cells) >= 4 else "High"
                ),
            )
            existing = sources.get(identifier)
            if existing is not None and existing != source:
                raise GenerationError(
                    f"{path}:{line_number}: conflicting definition for {identifier}"
                )
            sources[identifier] = source
    return sources


def recovered_evidence(requirements: list[Requirement]) -> str:
    references: list[str] = []
    for requirement in requirements:
        for candidate in re.findall(
            r"`([^`]+)`",
            f"{requirement.statement} {requirement.acceptance}",
        ):
            if "/" in candidate or "." in pathlib.PurePosixPath(candidate).name:
                references.append(candidate)
    if references:
        return "; ".join(f"`{item}`" for item in dict.fromkeys(references))
    identifiers = ", ".join(item.identifier for item in requirements)
    return (
        "Original source definition is absent from the package; provenance was "
        f"recovered only from the canonical statements and acceptance scenarios "
        f"for {identifiers}."
    )


def normalize_sources(
    requirements: tuple[Requirement, ...],
    explicit: dict[str, Source],
) -> tuple[tuple[Requirement, ...], tuple[Source, ...]]:
    used_numeric = [
        int(match.group(0).split("-")[1])
        for identifier in (
            source
            for requirement in requirements
            for source in requirement.sources
            if not source.startswith("RAW::")
        )
        if (match := SOURCE_ID.fullmatch(identifier)) is not None
    ]
    used_numeric.extend(
        int(identifier.split("-")[1]) for identifier in explicit
    )
    next_source = max(used_numeric, default=0) + 1
    raw_mapping: dict[str, str] = {}
    normalized_requirements: list[Requirement] = []
    for requirement in requirements:
        normalized: list[str] = []
        for source in requirement.sources:
            if not source.startswith("RAW::"):
                normalized.append(source)
                continue
            evidence = source.removeprefix("RAW::")
            identifier = raw_mapping.get(evidence)
            if identifier is None:
                while f"SRC-{next_source:03d}" in explicit:
                    next_source += 1
                identifier = f"SRC-{next_source:03d}"
                next_source += 1
                raw_mapping[evidence] = identifier
            normalized.append(identifier)
        normalized_requirements.append(
            dataclasses.replace(
                requirement,
                sources=tuple(dict.fromkeys(normalized)),
            )
        )

    requirements_by_source: dict[str, list[Requirement]] = collections.defaultdict(
        list
    )
    for requirement in normalized_requirements:
        for source in requirement.sources:
            requirements_by_source[source].append(requirement)

    sources = dict(explicit)
    for evidence, identifier in raw_mapping.items():
        governed = requirements_by_source[identifier]
        sources[identifier] = Source(
            identifier=identifier,
            evidence=evidence,
            relevance=(
                "Primary catalog evidence for "
                + ", ".join(item.identifier for item in governed)
                + "."
            ),
            confidence=(
                "High"
                if "/" in evidence or "." in pathlib.PurePosixPath(evidence).name
                else "Medium"
            ),
        )

    for identifier, governed in requirements_by_source.items():
        if identifier in sources:
            continue
        sources[identifier] = Source(
            identifier=identifier,
            evidence=recovered_evidence(governed),
            relevance=(
                "Recovered provenance for "
                + ", ".join(item.identifier for item in governed)
                + "; accountable source review is required."
            ),
            confidence="Low - recovered source definition",
        )
    return tuple(normalized_requirements), tuple(
        sources[identifier] for identifier in sorted(sources)
    )


def parse_sources(
    specification: str,
    analysis: str,
    requirements: tuple[Requirement, ...],
    specification_path: pathlib.Path,
    analysis_path: pathlib.Path,
) -> tuple[tuple[Requirement, ...], tuple[Source, ...]]:
    explicit = parse_explicit_sources(
        (
            (specification, specification_path),
            (analysis, analysis_path),
        )
    )
    return normalize_sources(requirements, explicit)


def legacy_parse_sources(text: str, path: pathlib.Path) -> tuple[Source, ...]:
    """Compatibility helper retained for downstream imports during migration."""
    sources: list[Source] = []
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) < 2 or SOURCE_ID.fullmatch(cells[0]) is None:
            continue
        sources.append(
            Source(
                identifier=cells[0],
                evidence=clean_cell(cells[1]),
                relevance=clean_cell(
                    cells[2] if len(cells) >= 3 else "Defined source evidence."
                ),
                confidence=clean_cell(cells[3] if len(cells) >= 4 else "High"),
            )
        )
    if not sources:
        raise GenerationError(f"{path}: no SRC evidence inventory rows found")
    identifiers = [item.identifier for item in sources]
    duplicates = sorted(
        identifier
        for identifier, count in collections.Counter(identifiers).items()
        if count > 1
    )
    if duplicates:
        raise GenerationError(f"{path}: duplicate source rows: {duplicates}")
    return tuple(sources)


def load_package(path: pathlib.Path) -> PackageEvidence:
    specification_path = path / "SPECIFICATION.md"
    analysis_path = path / "ANALYSIS.md"
    source_texts: dict[str, str] = {}
    source_hashes: dict[str, str] = {}
    for relative in (*CORE_ARTIFACTS, *CHECKPOINT_ARTIFACTS):
        source_path = path / relative
        try:
            raw = source_path.read_bytes()
            source_texts[relative] = raw.decode("utf-8").replace("\r\n", "\n").replace("\r", "\n")
        except (OSError, UnicodeDecodeError) as error:
            raise GenerationError(f"{source_path}: cannot read source: {error}") from error
        source_hashes[relative] = hashlib.sha256(raw).hexdigest()
    specification = source_texts["SPECIFICATION.md"]
    analysis = source_texts["ANALYSIS.md"]
    metadata = parse_frontmatter(specification, specification_path)
    checkpoint_data: list[dict[str, Any]] = []
    for relative in CHECKPOINT_ARTIFACTS:
        try:
            document = yaml.safe_load(source_texts[relative])
        except yaml.YAMLError as error:
            raise GenerationError(f"{path / relative}: invalid YAML: {error}") from error
        if not isinstance(document, dict):
            raise GenerationError(f"{path / relative}: expected a YAML mapping")
        checkpoint_data.append(document)
    spec_to_plan, plan_to_tasks, test_coverage = checkpoint_data
    parsed_requirements = parse_requirements(
        mask_fenced_content(specification),
        specification_path,
        default_status=lifecycle_status(metadata.get("status", "draft")),
        test_coverage=test_coverage,
    )
    requirements, sources = parse_sources(
        specification,
        analysis,
        parsed_requirements,
        specification_path,
        analysis_path,
    )

    feature = spec_to_plan.get("feature", {})
    if not isinstance(feature, dict):
        raise GenerationError(f"{path}: spec-to-plan feature must be a mapping")
    feature_id = str(feature.get("id", ""))
    slug = str(feature.get("slug", ""))
    expected_id, expected_slug = path.name.split("-", 1)
    if (feature_id, slug) != (expected_id, expected_slug):
        raise GenerationError(
            f"{path}: checkpoint identity {(feature_id, slug)!r} does not match "
            f"{(expected_id, expected_slug)!r}"
        )

    title = str(metadata.get("title", slug.replace("-", " ").title()))
    for prefix in ("Requirements: ", "Specification: "):
        if title.startswith(prefix):
            title = title[len(prefix):]
            break
    implementation_status = str(
        metadata.get("implementation_status", "Not started")
    )

    evidence = PackageEvidence(
        path=path,
        feature_id=feature_id,
        slug=slug,
        title=title,
        implementation_status=implementation_status,
        requirements=requirements,
        sources=sources,
        spec_to_plan=spec_to_plan,
        plan_to_tasks=plan_to_tasks,
        test_coverage=test_coverage,
        source_texts=source_texts,
        source_hashes=source_hashes,
    )
    validate_closure(evidence)
    return evidence


def requirement_maps(
    evidence: PackageEvidence,
) -> tuple[
    dict[str, list[str]],
    dict[str, list[str]],
    dict[str, list[str]],
    dict[str, list[str]],
]:
    design: dict[str, list[str]] = {}
    plans: dict[str, list[str]] = collections.defaultdict(list)
    tasks: dict[str, list[str]] = collections.defaultdict(list)
    tests: dict[str, list[str]] = {}

    spec_requirements = evidence.spec_to_plan.get("requirements", {})
    if not isinstance(spec_requirements, dict):
        raise GenerationError(
            f"{evidence.path}: spec-to-plan requirements must be a mapping"
        )
    for identifier, mapping in spec_requirements.items():
        if not isinstance(mapping, dict):
            raise GenerationError(
                f"{evidence.path}: invalid spec-to-plan entry for {identifier}"
            )
        design[str(identifier)] = [
            str(item) for item in mapping.get("design_components", [])
        ]
        plans[str(identifier)] = [
            str(item) for item in mapping.get("plan_items", [])
        ]

    plan_items = evidence.plan_to_tasks.get("plan_items", {})
    if not isinstance(plan_items, dict):
        raise GenerationError(
            f"{evidence.path}: plan-to-tasks plan_items must be a mapping"
        )
    for plan_id, plan in plan_items.items():
        if not isinstance(plan, dict):
            raise GenerationError(
                f"{evidence.path}: invalid plan-to-tasks entry for {plan_id}"
            )
        for identifier in plan.get("requirements", []):
            plans[str(identifier)].append(str(plan_id))
            tasks[str(identifier)].extend(str(item) for item in plan.get("tasks", []))

    coverage = evidence.test_coverage.get("requirements", {})
    if not isinstance(coverage, dict):
        raise GenerationError(
            f"{evidence.path}: test-coverage requirements must be a mapping"
        )
    for identifier, mapping in coverage.items():
        if not isinstance(mapping, dict):
            raise GenerationError(
                f"{evidence.path}: invalid test-coverage entry for {identifier}"
            )
        tests[str(identifier)] = [
            str(item) for item in mapping.get("tests", [])
        ]

    for mapping in (plans, tasks):
        for identifier, values in mapping.items():
            mapping[identifier] = list(dict.fromkeys(values))
    return design, plans, tasks, tests


def validate_closure(evidence: PackageEvidence) -> None:
    requirement_ids = {item.identifier for item in evidence.requirements}
    source_ids = {item.identifier for item in evidence.sources}
    design, plans, tasks, tests = requirement_maps(evidence)
    surfaces = {
        "spec-to-plan": set(design),
        "plan-to-tasks": set(tasks),
        "test-coverage": set(tests),
    }
    errors: list[str] = []
    for name, identifiers in surfaces.items():
        missing = sorted(requirement_ids - identifiers)
        extra = sorted(identifiers - requirement_ids)
        if missing or extra:
            errors.append(f"{name}: missing={missing}, extra={extra}")
    missing_sources = sorted(
        {
            source
            for requirement in evidence.requirements
            for source in requirement.sources
            if source not in source_ids
        }
    )
    if missing_sources:
        errors.append(f"source inventory misses {missing_sources}")
    for identifier in sorted(requirement_ids):
        if not design.get(identifier):
            errors.append(f"{identifier}: no design component")
        if not plans.get(identifier):
            errors.append(f"{identifier}: no plan item")
        if not tasks.get(identifier):
            errors.append(f"{identifier}: no task")
        if not tests.get(identifier):
            errors.append(f"{identifier}: no test")
    if errors:
        raise GenerationError(f"{evidence.path}: closure failure: {'; '.join(errors)}")


def frontmatter(evidence: PackageEvidence, artifact: str) -> str:
    title = artifact.removesuffix(".md").replace("_", " ").title()
    return "\n".join(
        (
            "---",
            f'title: "{title}: {evidence.title}"',
            f'feature_id: "{evidence.feature_id}-{evidence.slug}"',
            'version: "1.0.0"',
            f'date: "{evidence.generated_on}"',
            f'author: "{CONFIG.get("generatedAuthor", "Specification team")}"',
            'status: "Ready for review"',
            f'implementation_status: "{evidence.implementation_status}"',
            "---",
            "",
            GENERATED_MARKER,
            "",
        )
    )


def checkpoint_state(document: dict[str, Any], field: str) -> str:
    return clean_cell(document.get("checkpoint", {}).get(field, "not-recorded"))


def checkpoint_reason(document: dict[str, Any]) -> str:
    return clean_cell(document.get("gate", {}).get("reason", "No reason recorded."))


def render_checklist(evidence: PackageEvidence) -> str:
    requirement_count = len(evidence.requirements)
    task_count = len(
        {
            task
            for plan in evidence.plan_to_tasks.get("plan_items", {}).values()
            for task in plan.get("tasks", [])
        }
    )
    test_count = len(evidence.test_coverage.get("tests", {}))
    spec_mapping = checkpoint_state(evidence.spec_to_plan, "mapping_status")
    task_mapping = checkpoint_state(evidence.plan_to_tasks, "mapping_status")
    test_mapping = checkpoint_state(evidence.test_coverage, "mapping_status")
    approval = checkpoint_state(evidence.spec_to_plan, "approval_status")
    implementation = checkpoint_state(
        evidence.plan_to_tasks, "implementation_status"
    )
    execution = checkpoint_state(evidence.test_coverage, "execution_status")
    complete_mapping = all(
        state.lower() == "complete"
        for state in (spec_mapping, task_mapping, test_mapping)
    )
    mapping_mark = "x" if complete_mapping else " "
    approval_mark = "x" if approval.lower() == "approved" else " "
    execution_mark = "x" if execution.lower() in {"passed", "complete"} else " "
    artifacts = CORE_ARTIFACTS + SUPPORT_ARTIFACTS
    artifact_rows = "\n".join(
        f"| `{name}` | {'PASS' if (evidence.path / name).exists() or name in SUPPORT_ARTIFACTS else 'FAIL'} | "
        f"{'Canonical or generated evidence surface.' if (evidence.path / name).exists() or name in SUPPORT_ARTIFACTS else 'Required artifact is absent.'} |"
        for name in artifacts
    )
    return (
        frontmatter(evidence, "CHECKLIST.md")
        + f"# Readiness Checklist: {evidence.title}\n\n"
        "## Purpose and evidence boundary\n\n"
        "This checklist evaluates review readiness from the canonical documents "
        "and machine-readable checkpoints in this package. A checked mapping item "
        "means the recorded sets close; it does not mean implementation, cloud "
        "mutation, approval, or runtime verification occurred.\n\n"
        "## Feature Metadata\n\n"
        "| Field | Value |\n| --- | --- |\n"
        f"| Feature | `{evidence.feature_id}-{evidence.slug}` |\n"
        f"| Requirements | {requirement_count} |\n"
        f"| Tasks | {task_count} |\n"
        f"| Tests | {test_count} |\n"
        f"| Package implementation claim | `{clean_cell(evidence.implementation_status)}` |\n"
        f"| Evidence snapshot | `{evidence.generated_on}` |\n\n"
        f"Active requirement IDs: "
        f"{clean_cell(', '.join(item.identifier for item in evidence.requirements))}.\n\n"
        "## Artifact integrity gate\n\n"
        "| Artifact | Result | Evidence |\n| --- | --- | --- |\n"
        f"{artifact_rows}\n\n"
        "## Requirements and traceability gate\n\n"
        f"- [{mapping_mark}] **CK-SDD-001** Requirement-to-design and plan mapping "
        f"is `{spec_mapping}` for all {requirement_count} requirements. Evidence: "
        "[`checkpoints/spec-to-plan.yaml`](checkpoints/spec-to-plan.yaml).\n"
        f"- [{mapping_mark}] **CK-SDD-002** Plan-to-task mapping is `{task_mapping}` "
        f"for {task_count} tasks. Evidence: "
        "[`checkpoints/plan-to-tasks.yaml`](checkpoints/plan-to-tasks.yaml).\n"
        f"- [{mapping_mark}] **CK-SDD-003** Requirement-to-test mapping is "
        f"`{test_mapping}` for {test_count} tests. Evidence: "
        "[`checkpoints/test-coverage.yaml`](checkpoints/test-coverage.yaml).\n"
        "- [x] **CK-SDD-004** Every active requirement names at least one `SRC-*` "
        "record present in the analysis evidence inventory. Evidence: "
        "[`SOURCE_TRACEABILITY.md`](SOURCE_TRACEABILITY.md).\n"
        "- [x] **CK-SDD-005** The root "
        "[`CONSTITUTION.md`](../CONSTITUTION.md) is reused; no feature-local "
        "constitution is required.\n\n"
        "## Approval and implementation gate\n\n"
        f"- [{approval_mark}] **CK-APPROVAL-001** Checkpoint approval status is "
        f"`{approval}`. An unchecked item blocks implementation authorization.\n"
        f"- [{'x' if implementation.lower() in {'implemented', 'complete', 'verified'} else ' '}] "
        f"**CK-IMPLEMENTATION-001** Checkpoint implementation status is "
        f"`{implementation}`. Partial or not-started work remains open.\n"
        f"- [{execution_mark}] **CK-VERIFICATION-001** Checkpoint execution status "
        f"is `{execution}`. Planned tests are not execution evidence.\n\n"
        "## Open conditions recorded by authoritative checkpoints\n\n"
        "| Checkpoint | Gate result | Recorded condition |\n| --- | --- | --- |\n"
        f"| Specification to plan | `{clean_cell(evidence.spec_to_plan.get('gate', {}).get('result', 'not-recorded'))}` | {checkpoint_reason(evidence.spec_to_plan)} |\n"
        f"| Plan to tasks | `{clean_cell(evidence.plan_to_tasks.get('gate', {}).get('result', 'not-recorded'))}` | {checkpoint_reason(evidence.plan_to_tasks)} |\n"
        f"| Requirement to test | `{clean_cell(evidence.test_coverage.get('gate', {}).get('result', 'not-recorded'))}` | {checkpoint_reason(evidence.test_coverage)} |\n\n"
        "## Completion decision\n\n"
        f"Structural mapping closure is {'PASS' if complete_mapping else 'FAIL'}. "
        f"Approval is `{approval}`, implementation is `{implementation}`, and test "
        f"execution is `{execution}`. The package therefore remains ready only for "
        "the review state supported by those records; this checklist grants no "
        "higher lifecycle state.\n\n"
        "## Change Log\n\n"
        "| Date | Version | Change |\n| --- | --- | --- |\n"
        f"| {evidence.generated_on} | 1.0.0 | Materialized the canonical ten-artifact review checklist from package evidence. |\n\n"
        "## References\n\n"
        "- [`SPECIFICATION.md`](SPECIFICATION.md)\n"
        "- [`ANALYSIS.md`](ANALYSIS.md)\n"
        "- [`TASKS.md`](TASKS.md)\n"
        "- [`TESTING.md`](TESTING.md)\n"
        "- [`DECISIONS.md`](DECISIONS.md)\n"
        "- [`CONSTITUTION.md`](../CONSTITUTION.md)\n"
    )


def render_cross_analysis(evidence: PackageEvidence) -> str:
    design, plans, tasks, tests = requirement_maps(evidence)
    requirement_rows = []
    for requirement in evidence.requirements:
        identifier = requirement.identifier
        requirement_rows.append(
            "| "
            + " | ".join(
                (
                    identifier,
                    ", ".join(requirement.sources),
                    clean_cell(", ".join(design[identifier])),
                    clean_cell(", ".join(plans[identifier])),
                    clean_cell(", ".join(tasks[identifier])),
                    clean_cell(", ".join(tests[identifier])),
                    clean_cell(requirement.lifecycle_status),
                )
            )
            + " |"
        )
    plan_rows = []
    for plan_id, plan in evidence.plan_to_tasks.get("plan_items", {}).items():
        plan_rows.append(
            "| "
            + " | ".join(
                (
                    str(plan_id),
                    clean_cell(plan.get("title", "")),
                    clean_cell(", ".join(str(item) for item in plan.get("requirements", []))),
                    clean_cell(", ".join(str(item) for item in plan.get("tasks", []))),
                    clean_cell(", ".join(str(item) for item in plan.get("depends_on", [])) or "none"),
                )
            )
            + " |"
        )
    requirement_ids = {item.identifier for item in evidence.requirements}
    task_ids = {
        str(task)
        for plan in evidence.plan_to_tasks.get("plan_items", {}).values()
        for task in plan.get("tasks", [])
    }
    test_ids = set(str(item) for item in evidence.test_coverage.get("tests", {}))
    return (
        frontmatter(evidence, "CROSS_ANALYSIS.md")
        + f"# Cross-Artifact Analysis: {evidence.title}\n\n"
        "## Purpose and result\n\n"
        "This document joins primary sources, canonical requirements, design "
        "components, plan items, tasks, and planned tests without redefining the "
        "requirements. The machine-readable checkpoints are the mapping source; "
        "the lifecycle status remains owned by the specification and verification "
        "evidence.\n\n"
        "## Feature Metadata\n\n"
        "| Field | Value |\n| --- | --- |\n"
        f"| Feature | `{evidence.feature_id}-{evidence.slug}` |\n"
        f"| Requirements | {len(requirement_ids)} |\n"
        f"| Tasks | {len(task_ids)} |\n"
        f"| Tests | {len(test_ids)} |\n"
        f"| Implementation claim | `{clean_cell(evidence.implementation_status)}` |\n"
        f"| Mapping snapshot | `{evidence.generated_on}` |\n\n"
        "## Requirement-to-delivery matrix\n\n"
        "| Requirement | Primary source(s) | Design components | Plan items | Tasks | Tests or evidence | Requirement lifecycle |\n"
        "| --- | --- | --- | --- | --- | --- | --- |\n"
        + "\n".join(requirement_rows)
        + "\n\n"
        "## Dependency analysis\n\n"
        "| Plan item | Purpose | Requirements | Tasks | Depends on |\n"
        "| --- | --- | --- | --- | --- |\n"
        + "\n".join(plan_rows)
        + "\n\n"
        "## Orphan and closure analysis\n\n"
        "| Set | Expected | Mapped | Orphans | Result |\n| --- | ---: | ---: | ---: | --- |\n"
        f"| Requirements to design/plan | {len(requirement_ids)} | {len(design)} | {len(requirement_ids - set(design))} | {'PASS' if requirement_ids == set(design) else 'FAIL'} |\n"
        f"| Requirements to tasks | {len(requirement_ids)} | {len(tasks)} | {len(requirement_ids - set(tasks))} | {'PASS' if requirement_ids == set(tasks) else 'FAIL'} |\n"
        f"| Requirements to tests | {len(requirement_ids)} | {len(tests)} | {len(requirement_ids - set(tests))} | {'PASS' if requirement_ids == set(tests) else 'FAIL'} |\n"
        f"| Declared tasks | {len(task_ids)} | {len(task_ids)} | 0 | PASS |\n"
        f"| Declared tests | {len(test_ids)} | {len(test_ids)} | 0 | PASS |\n\n"
        "## Status and tension analysis\n\n"
        f"- Specification mapping gate: `{clean_cell(evidence.spec_to_plan.get('gate', {}).get('result', 'not-recorded'))}` — {checkpoint_reason(evidence.spec_to_plan)}\n"
        f"- Task mapping gate: `{clean_cell(evidence.plan_to_tasks.get('gate', {}).get('result', 'not-recorded'))}` — {checkpoint_reason(evidence.plan_to_tasks)}\n"
        f"- Test mapping gate: `{clean_cell(evidence.test_coverage.get('gate', {}).get('result', 'not-recorded'))}` — {checkpoint_reason(evidence.test_coverage)}\n"
        f"- Package implementation claim: `{clean_cell(evidence.implementation_status)}`. Mapping closure does not raise that claim.\n\n"
        "## Lifecycle and disposition policy\n\n"
        "Stable requirement IDs remain canonical in "
        "[`SPECIFICATION.md`](SPECIFICATION.md). Any future split, merge, transfer, "
        "supersession, or retirement must be recorded there and in "
        "[`SOURCE_TRACEABILITY.md`](SOURCE_TRACEABILITY.md); this generated matrix "
        "must then be regenerated so removed or orphaned mappings fail closure.\n\n"
        "## Change Log\n\n"
        "| Date | Version | Change |\n| --- | --- | --- |\n"
        f"| {evidence.generated_on} | 1.0.0 | Materialized end-to-end requirement delivery closure from checkpoints. |\n\n"
        "## References\n\n"
        "- [`SPECIFICATION.md`](SPECIFICATION.md)\n"
        "- [`DESIGN.md`](DESIGN.md)\n"
        "- [`TASKS.md`](TASKS.md)\n"
        "- [`TESTING.md`](TESTING.md)\n"
        "- [`checkpoints/spec-to-plan.yaml`](checkpoints/spec-to-plan.yaml)\n"
        "- [`checkpoints/plan-to-tasks.yaml`](checkpoints/plan-to-tasks.yaml)\n"
        "- [`checkpoints/test-coverage.yaml`](checkpoints/test-coverage.yaml)\n"
    )


def render_verification(evidence: PackageEvidence) -> str:
    coverage = evidence.test_coverage.get("requirements", {})
    test_catalog = evidence.test_coverage.get("tests", {})
    reverse: dict[str, list[str]] = collections.defaultdict(list)
    for identifier, mapping in coverage.items():
        for test_id in mapping.get("tests", []):
            reverse[str(test_id)].append(str(identifier))
    test_rows = []
    for test_id, definition in test_catalog.items():
        if not isinstance(definition, dict):
            raise GenerationError(
                f"{evidence.path}: test {test_id} definition must be a mapping"
            )
        test_rows.append(
            "| "
            + " | ".join(
                (
                    str(test_id),
                    clean_cell(definition.get("tier", "not-recorded")),
                    code_cell(definition.get("file", "not-recorded")),
                    clean_cell(", ".join(reverse[str(test_id)])),
                    "Planned or recorded; see execution state below",
                )
            )
            + " |"
        )
    requirement_rows = []
    for requirement in evidence.requirements:
        tests = coverage[requirement.identifier].get("tests", [])
        requirement_rows.append(
            f"| {requirement.identifier} | {clean_cell(requirement.acceptance)} | "
            f"{clean_cell(', '.join(str(item) for item in tests))} | "
            f"{clean_cell(requirement.verification)} |"
        )
    execution = checkpoint_state(evidence.test_coverage, "execution_status")
    approval = checkpoint_state(evidence.test_coverage, "approval_status")
    mapping_status = checkpoint_state(
        evidence.test_coverage, "mapping_status"
    )
    mapping_result = (
        "PASS" if mapping_status.lower() == "complete" else "FAIL"
    )
    execution_result = (
        "PASS"
        if execution.lower() in {"executed", "passed", "complete", "verified"}
        else execution.upper().replace("_", " ")
    )
    partial_blocker = (
        "\nStill blocked: "
        + checkpoint_reason(evidence.plan_to_tasks)
        + "\n"
        if evidence.implementation_status.lower().startswith("partial")
        else ""
    )
    return (
        frontmatter(evidence, "VERIFICATION.md")
        + f"# Verification Record: {evidence.title}\n\n"
        "## Evidence truth rules\n\n"
        "- `PASS` requires a named command or inspection to have executed "
        "successfully with retained evidence.\n"
        "- `BLOCKED` means a mandatory prerequisite or approval is absent.\n"
        "- `NOT RUN` means the mapping exists but no execution evidence is claimed.\n"
        "- A checkpoint mapping, design statement, or planned test is not runtime "
        "evidence.\n"
        "- Cloud or deployment state is never inferred from static validation.\n\n"
        "## Feature Metadata\n\n"
        "| Field | Value |\n| --- | --- |\n"
        f"| Feature | `{evidence.feature_id}-{evidence.slug}` |\n"
        f"| Requirement count | {len(evidence.requirements)} |\n"
        f"| Test count | {len(test_catalog)} |\n"
        f"| Mapping status | `{checkpoint_state(evidence.test_coverage, 'mapping_status')}` |\n"
        f"| Execution status | `{execution}` |\n"
        f"| Approval status | `{approval}` |\n"
        f"| Evidence snapshot | `{evidence.generated_on}` |\n\n"
        "## Verification summary\n\n"
        "| Check | Result | Evidence |\n| --- | --- | --- |\n"
        f"| Requirement-to-test mapping closure | {mapping_result} | "
        f"`checkpoints/test-coverage.yaml` reports `{mapping_status}`. |\n"
        f"| Recorded test execution | {execution_result} | "
        f"Checkpoint execution status is `{execution}`. |\n"
        f"| Approval | {approval.upper()} | "
        f"Checkpoint approval status is `{approval}`. |\n"
        f"{partial_blocker}\n"
        "## Requirement verification map\n\n"
        "| Requirement | Acceptance signal | Planned tests | Verification method |\n"
        "| --- | --- | --- | --- |\n"
        + "\n".join(requirement_rows)
        + "\n\n"
        "## Test and evidence inventory\n\n"
        "| Test ID | Tier | Evidence surface or command | Governing requirements | Current evidence state |\n"
        "| --- | --- | --- | --- | --- |\n"
        + "\n".join(test_rows)
        + "\n\n"
        "## Deterministic validation order\n\n"
        "1. Run the package commands and failure-injection cases defined in "
        "[`TESTING.md`](TESTING.md).\n"
        "2. Run `python3 .github/scripts/validate-spec-artifacts.py "
        f".spec/{evidence.path.name}`.\n"
        "3. Run `python3 .github/scripts/validate-sdd-documents.py "
        f"--package {evidence.path.name}`.\n"
        "4. Run `python3 .github/scripts/validate-design-diagrams.py --spec-root "
        f".spec/{evidence.path.name}`.\n"
        "5. Run `python3 .github/scripts/validate-specs.py --spec-root .spec --strict` "
        "for checkpoint and contract closure.\n"
        "6. Run `python3 .github/scripts/validate-spec-status.py .spec`, "
        "`python3 .github/scripts/validate-task-graph.py --all`, and "
        "`python3 .github/scripts/validate-testing-evidence.py` before a program-level "
        "readiness claim.\n\n"
        "## Current verification decision\n\n"
        f"Requirement-to-test mapping is "
        f"`{checkpoint_state(evidence.test_coverage, 'mapping_status')}`. "
        f"Execution is `{execution}` and approval is `{approval}`. "
        f"{checkpoint_reason(evidence.test_coverage)} No stronger verification "
        "claim is made by this record.\n\n"
        "## Exit criteria\n\n"
        "- Every applicable planned test has an executed result and retained "
        "evidence.\n"
        "- Required negative and failure-path cases in `TESTING.md` execute.\n"
        "- No active requirement is missing test coverage.\n"
        "- Approval and implementation claims agree with the canonical status "
        "documents.\n"
        "- All repository SDD gates pass without weakening or baseline expansion.\n\n"
        "## Change Log\n\n"
        "| Date | Version | Change |\n| --- | --- | --- |\n"
        f"| {evidence.generated_on} | 1.0.0 | Materialized the requirement and test evidence record without inferring execution. |\n\n"
        "## References\n\n"
        "- [`SPECIFICATION.md`](SPECIFICATION.md)\n"
        "- [`TESTING.md`](TESTING.md)\n"
        "- [`TASKS.md`](TASKS.md)\n"
        "- [`CHECKLIST.md`](CHECKLIST.md)\n"
        "- [`checkpoints/test-coverage.yaml`](checkpoints/test-coverage.yaml)\n"
    )


def render_source_traceability(evidence: PackageEvidence) -> str:
    source_rows = "\n".join(
        f"| {source.identifier} | {source.evidence} | {source.relevance} | "
        f"{source.confidence} |"
        for source in evidence.sources
    )
    requirement_rows = "\n".join(
        f"| {requirement.identifier} | {clean_cell(', '.join(requirement.sources))} | "
        f"{clean_cell(requirement.statement)} | {requirement.priority} | "
        f"{requirement.lifecycle_status} |"
        for requirement in evidence.requirements
    )
    used_sources = {
        source
        for requirement in evidence.requirements
        for source in requirement.sources
    }
    inventory_sources = {source.identifier for source in evidence.sources}
    unused = sorted(inventory_sources - used_sources)
    return (
        frontmatter(evidence, "SOURCE_TRACEABILITY.md")
        + f"# Source Traceability: {evidence.title}\n\n"
        "## Source policy\n\n"
        "Primary provenance is owned by the canonical requirement records in "
        "[`SPECIFICATION.md`](SPECIFICATION.md) and the dated evidence inventory "
        "in [`ANALYSIS.md`](ANALYSIS.md). This document joins those records; it "
        "does not replace the original source or convert a planned artifact into "
        "execution evidence.\n\n"
        "## Feature Metadata\n\n"
        "| Field | Value |\n| --- | --- |\n"
        f"| Feature | `{evidence.feature_id}-{evidence.slug}` |\n"
        f"| Active requirements | {len(evidence.requirements)} |\n"
        f"| Source inventory | {len(evidence.sources)} |\n"
        f"| Sources referenced by requirements | {len(used_sources)} |\n"
        f"| Evidence snapshot | `{evidence.generated_on}` |\n\n"
        "## Source inventory\n\n"
        "| Source ID | Evidence | Relevance | Confidence |\n"
        "| --- | --- | --- | --- |\n"
        f"{source_rows}\n\n"
        "## Requirement provenance matrix\n\n"
        "| Requirement | Primary source(s) | Canonical response summary | Priority | Lifecycle status |\n"
        "| --- | --- | --- | --- | --- |\n"
        f"{requirement_rows}\n\n"
        "## Coverage and disposition\n\n"
        f"- Requirements with at least one primary source: "
        f"{len(evidence.requirements)} of {len(evidence.requirements)}.\n"
        f"- Referenced sources present in the evidence inventory: "
        f"{len(used_sources)} of {len(used_sources)}.\n"
        f"- Inventory sources not directly assigned to an active requirement: "
        f"{clean_cell(', '.join(unused) if unused else 'none')}.\n"
        "- Any future split, merge, transfer, supersession, or retirement must "
        "preserve the stable ID in a disposition record before regeneration.\n"
        "- External URLs or platform facts remain bounded by the retrieval date "
        "and confidence recorded in `ANALYSIS.md`.\n\n"
        "## Change Log\n\n"
        "| Date | Version | Change |\n| --- | --- | --- |\n"
        f"| {evidence.generated_on} | 1.0.0 | Materialized one provenance row for every active requirement. |\n\n"
        "## References\n\n"
        "- [`SPECIFICATION.md`](SPECIFICATION.md)\n"
        "- [`ANALYSIS.md`](ANALYSIS.md)\n"
        "- [`DECISIONS.md`](DECISIONS.md)\n"
        "- [`CROSS_ANALYSIS.md`](CROSS_ANALYSIS.md)\n"
        "- [`CONSTITUTION.md`](../CONSTITUTION.md)\n"
    )


def canonical_diagram_command(evidence: PackageEvidence) -> str:
    return (
        "python3 .github/scripts/validate-design-diagrams.py --spec-root "
        f".spec/{evidence.path.name}"
    )


def supplement_provenance(evidence: PackageEvidence) -> str:
    hashes = "\n".join(
        f"| [`{path}`]({path}) | `{digest}` |"
        for path, digest in sorted(evidence.source_hashes.items())
    )
    return (
        "## Provenance and authority\n\n"
        "This generated review projection preserves canonical source content; "
        "it is not a new requirements authority or an execution report. "
        "Hashes bind original bytes; parsing normalizes line endings only. "
        "`SPECIFICATION.md`, `TASKS.md`, `TESTING.md`, decisions and checkpoints "
        "remain authoritative. Generation does not verify execution, approval "
        "or live acceptance. Missing source details below require author review; "
        "they are not permission to substitute generic scenarios or results.\n\n"
        "| Source snapshot | SHA-256 |\n| --- | --- |\n"
        f"{hashes}\n\n"
    )


def mask_fenced_content(text: str) -> str:
    """Keep character offsets while excluding fenced examples from parsing."""
    masked: list[str] = []
    fence: tuple[str, int] | None = None
    for line in text.splitlines(keepends=True):
        marker = re.match(r"^[ \t]*(`{3,}|~{3,})(.*)$", line.rstrip("\r\n"))
        hide = fence is not None or marker is not None
        if marker is not None:
            delimiter = marker[1]
            if fence is None:
                fence = (delimiter[0], len(delimiter))
            elif (
                delimiter[0] == fence[0]
                and len(delimiter) >= fence[1]
                and not marker[2].strip()
            ):
                fence = None
        masked.append(
            "".join(character if character in "\r\n" else " " for character in line)
            if hide else line
        )
    return "".join(masked)


def source_sections(text: str, terms: tuple[str, ...]) -> str:
    """Copy named source sections without interpreting headings inside fences."""
    lines = text.splitlines()
    masked = mask_fenced_content(text).splitlines()
    headings: list[tuple[int, int, str]] = []
    for index, line in enumerate(masked):
        match = re.match(r"^(#{1,6})\s+(.+?)\s*#*\s*$", line)
        if match:
            headings.append((index, len(match[1]), match[2].lower()))
    result: list[str] = []
    consumed_until = -1
    for position, (start, level, title) in enumerate(headings):
        if start < consumed_until or not any(term in title for term in terms):
            continue
        end = next(
            (line for line, depth, _ in headings[position + 1:] if depth <= level),
            len(lines),
        )
        block = lines[start:end]
        # Copied headings sit one level below the wrapper heading that introduces them.
        block = [re.sub(r"^(#{1,5})(\s)", r"#\1\2", line) if masked[start + index] == line else line
                 for index, line in enumerate(block)]
        result.append("\n".join(block).strip())
        consumed_until = end
    return "\n\n".join(result)


def source_table_rows(text: str, identifiers: set[str], prefix: str) -> str:
    """Retain whole rows and their headers, including Given/When/Then columns."""
    lines = text.splitlines()
    header: tuple[str, str] | None = None
    emitted_header: tuple[str, str] | None = None
    result: list[str] = []
    for index, line in enumerate(mask_fenced_content(text).splitlines()):
        if index and re.fullmatch(r"\|[\s:|-]+\|", line.strip()):
            header = (lines[index - 1], lines[index])
            continue
        if not re.match(rf"^\|\s*{re.escape(prefix)}", line):
            continue
        found = set(re.findall(r"\b(?:REQ|NFR|TST)-[A-Z]*\d{3}\b", line))
        if not found.intersection(identifiers):
            continue
        if header is not None and header != emitted_header:
            result.extend(("", *header))
            emitted_header = header
        result.append(lines[index])
    return "\n".join(result).strip()


def source_requirement_blocks(evidence: PackageEvidence) -> dict[str, str]:
    text = evidence.source_texts["SPECIFICATION.md"]
    masked = mask_fenced_content(text)
    blocks: dict[str, str] = {}
    for match in REQUIREMENT_BLOCK.finditer(masked):
        if match["id"] in blocks:
            raise GenerationError(f"{evidence.path}: duplicate requirement {match['id']}")
        heading = re.search(r"(?m)^#{1,6}\s", match[0])
        end = match.start() + heading.start() if heading else match.end()
        blocks[match["id"]] = text[match.start():end].strip()
    return blocks


def source_task_blocks(evidence: PackageEvidence) -> dict[str, str]:
    text = evidence.source_texts["TASKS.md"]
    blocks: dict[str, str] = {}
    for match in TASK_SOURCE_BLOCK.finditer(mask_fenced_content(text)):
        if match["id"] in blocks:
            raise GenerationError(f"{evidence.path}: duplicate task {match['id']}")
        blocks[match["id"]] = text[match.start():match.end()].strip()
    return blocks


def source_acceptance(evidence: PackageEvidence, requirement: Requirement) -> str:
    block = source_requirement_blocks(evidence).get(requirement.identifier, "")
    lines = block.splitlines()
    for index, line in enumerate(lines):
        match = re.match(r"^(\s*)-\s+Acceptance:\s*(.*)$", line)
        if match is None:
            continue
        indentation = len(match[1])
        values = [match[2]]
        for continuation in lines[index + 1:]:
            field = re.match(
                r"^(\s*)-\s+(?:Pattern|Priority|Rationale|Verification|Source|Status):",
                continuation,
            )
            if field and len(field[1]) <= indentation:
                break
            values.append(continuation)
        return clean_cell("\n".join(values))
    return requirement.acceptance


def requirement_declarations(
    evidence: PackageEvidence, requirements: list[Requirement]
) -> str:
    specification = evidence.source_texts["SPECIFICATION.md"]
    raw = source_requirement_blocks(evidence)
    sections: list[str] = []
    for requirement in requirements:
        declaration = raw.get(requirement.identifier)
        if declaration is None:
            declaration = (
                f"{requirement.statement}\n\n"
                "The canonical parser recovered this record; consult the source "
                "specification for its complete acceptance record."
            )
        sections.append(f"### {requirement.identifier}\n\n{declaration}")
    rows = source_table_rows(
        specification, {item.identifier for item in requirements}, "AC-"
    )
    if rows:
        sections.append("## Canonical acceptance scenarios\n\n" + rows)
    return "\n\n".join(sections)


def document_checks(evidence: PackageEvidence) -> str:
    return (
        "## Document quality checks\n\n"
        "These validate the documents, not the behavior of each mapped test:\n\n"
        "```bash\n"
        f"python3 .github/scripts/validate-spec-artifacts.py .spec/{evidence.path.name}\n"
        f"{canonical_diagram_command(evidence)}\n"
        f"python3 .github/scripts/validate-sdd-documents.py --package {evidence.path.name}\n"
        "```\n"
    )


def render_frd(evidence: PackageEvidence) -> str:
    design, _plans, _tasks, _tests = requirement_maps(evidence)
    functional = [
        item for item in evidence.requirements if item.identifier.startswith("REQ-")
    ]
    rows = "\n".join(
        f"| {item.identifier} | {clean_cell(item.statement)} | {item.priority} | "
        f"{clean_cell(', '.join(item.sources))} | "
        f"{clean_cell(', '.join(design.get(item.identifier, [])) or 'MISSING SOURCE EVIDENCE: no design/scope mapping for ' + item.identifier)} | "
        f"{source_acceptance(evidence, item)} | {clean_cell(item.verification)} |"
        for item in functional
    )
    if not rows:
        rows = (
            "| _none_ | MISSING SOURCE EVIDENCE: no REQ-* functional requirements "
            "found in SPECIFICATION.md | | | | | |"
        )
    context = source_sections(
        evidence.source_texts["SPECIFICATION.md"],
        ("problem", "outcome", "scope", "actor", "dependenc", "assumption"),
    )
    return (
        frontmatter(evidence, "FRD.md")
        + f"# Functional Requirements Document: {evidence.title}\n\n"
        + supplement_provenance(evidence)
        + (context or "Source context is not separately structured; review `SPECIFICATION.md`.")
        + "\n\n## Functional requirement index\n\n"
        "| ID | Statement | Priority | Source(s) | Linked scope/interfaces | "
        "Acceptance criteria | Verification method |\n"
        "| --- | --- | --- | --- | --- | --- | --- |\n"
        f"{rows}\n\n"
        "The index is a navigation aid. Complete declarations and acceptance "
        "scenarios below retain source conditions, actions and assertions.\n\n"
        + requirement_declarations(evidence, functional)
        + "\n\n"
        + document_checks(evidence)
    )


def render_nfrd(evidence: PackageEvidence) -> str:
    quality = [
        item for item in evidence.requirements if item.identifier.startswith("NFR-")
    ]
    rows = "\n".join(
        f"| {item.identifier} | {clean_cell(item.statement)} | {item.priority} | "
        f"{clean_cell(', '.join(item.sources))} | {clean_cell(item.statement)} | "
        f"{source_acceptance(evidence, item)} | {clean_cell(item.verification)} |"
        for item in quality
    )
    if not rows:
        rows = (
            "| _none_ | No NFR-* quality requirements are declared in this "
            "package's SPECIFICATION.md. | | | | | |"
        )
    return (
        frontmatter(evidence, "NFRD.md")
        + f"# Non-Functional Requirements Document: {evidence.title}\n\n"
        + supplement_provenance(evidence)
        + "## Measurement and constraint context\n\n"
        "Complete declarations below retain qualitative constraints and every "
        "numeric target, comparator and condition; no single-number extraction "
        "or additional measurement values are inferred. Missing workload, "
        "aggregation, observation window, environment or instrumentation must "
        "be resolved from the canonical sources before measured acceptance. "
        "This projection does not certify that a measurement envelope is complete.\n\n"
        + source_sections(
            evidence.source_texts["SPECIFICATION.md"],
            ("measurement", "assumption", "constraint", "dependenc", "open decision"),
        )
        + "\n\n"
        "## Quality Requirements\n\n"
        "| ID | Statement | Priority | Source(s) | Measurement/constraint | "
        "Acceptance criteria | Verification method |\n"
        "| --- | --- | --- | --- | --- | --- | --- |\n"
        f"{rows}\n\n"
        + requirement_declarations(evidence, quality)
        + "\n\n"
        + document_checks(evidence)
    )


def ordered_plans(evidence: PackageEvidence) -> list[str]:
    plans = evidence.plan_to_tasks.get("plan_items", {})
    if not isinstance(plans, dict):
        raise GenerationError(f"{evidence.path}: plan_items must be a mapping")
    remaining = set(plans)
    dependencies: dict[str, set[str]] = {}
    for name, plan in plans.items():
        if not isinstance(plan, dict):
            raise GenerationError(f"{evidence.path}: plan {name} must be a mapping")
        declared = plan.get("depends_on", [])
        if not isinstance(declared, list) or not all(isinstance(dep, str) for dep in declared):
            raise GenerationError(f"{evidence.path}: plan {name} has invalid dependencies")
        dependencies[name] = set(declared).intersection(plans)
    ordered: list[str] = []
    while remaining:
        ready = sorted(name for name in remaining if not dependencies[name].intersection(remaining))
        if not ready:
            raise GenerationError(f"{evidence.path}: cyclic plan dependencies: {sorted(remaining)}")
        ordered.extend(ready)
        remaining.difference_update(ready)
    return ordered


def declared_test_command(definition: dict[str, Any], test_id: str) -> str | None:
    command = definition.get("command")
    if isinstance(command, str) and command.strip():
        content = command
        language = "text"
    elif isinstance(command, list) and command and all(isinstance(arg, str) for arg in command):
        content = json.dumps(command, ensure_ascii=True, indent=2)
        language = "json"
    elif command is None:
        return None
    else:
        raise GenerationError(f"test {test_id}: malformed declared command")
    longest = max((len(match[0]) for match in re.finditer(r"`+", content)), default=0)
    fence = "`" * max(3, longest + 1)
    closing_newline = "" if content.endswith("\n") else "\n"
    return f"{fence}{language}\n{content}{closing_newline}{fence}"


def render_tdd(evidence: PackageEvidence) -> str:
    _design, _plans, _tasks, tests = requirement_maps(evidence)
    plan_items = evidence.plan_to_tasks.get("plan_items", {})
    test_meta = evidence.test_coverage.get("tests", {})
    if not isinstance(test_meta, dict):
        raise GenerationError(f"{evidence.path}: tests must be a mapping")
    plan_order = ordered_plans(evidence)
    ordered_tasks: list[str] = []
    task_requirements: dict[str, list[str]] = collections.defaultdict(list)
    task_plans: dict[str, list[str]] = collections.defaultdict(list)
    task_dependencies: dict[str, set[str]] = collections.defaultdict(set)
    for plan_id in plan_order:
        plan = plan_items[plan_id]
        for task_id in plan.get("tasks", []):
            task_id = str(task_id)
            if task_id not in ordered_tasks:
                ordered_tasks.append(task_id)
            task_plans[task_id].append(plan_id)
            task_dependencies[task_id].update(plan.get("depends_on", []))
            for requirement_id in plan.get("requirements", []):
                requirement_id = str(requirement_id)
                if requirement_id not in task_requirements[task_id]:
                    task_requirements[task_id].append(requirement_id)

    task_sources = source_task_blocks(evidence)

    sections: list[str] = []
    for task_id in ordered_tasks:
        requirement_ids = task_requirements.get(task_id, [])
        dependencies = sorted(task_dependencies.get(task_id, set()))
        test_rows: list[str] = []
        command_blocks: dict[str, str] = {}
        for requirement_id in requirement_ids:
            requirement = next(
                (
                    item
                    for item in evidence.requirements
                    if item.identifier == requirement_id
                ),
                None,
            )
            acceptance = source_acceptance(evidence, requirement) if requirement else (
                f"MISSING SOURCE EVIDENCE: {requirement_id} not found in "
                "SPECIFICATION.md"
            )
            for test_id in tests.get(requirement_id, []):
                meta = test_meta.get(test_id, {})
                if not isinstance(meta, dict):
                    raise GenerationError(f"{evidence.path}: test {test_id} must be a mapping")
                surface = clean_cell(meta.get("file", "not-recorded"))
                tier = clean_cell(meta.get("tier", "not-recorded"))
                declared = declared_test_command(meta, test_id)
                if declared is None:
                    command = (
                        "No explicit per-test command binding; see source-declared "
                        "package commands. A document validator is not substituted."
                    )
                else:
                    command = "Explicit checkpoint command; preserved verbatim below."
                    command_blocks[str(test_id)] = declared
                test_rows.append(
                    f"| {test_id} | {requirement_id} | `{surface}` | {tier} | "
                    f"{acceptance} | {command} |"
                )
        dependency_text = clean_cell(
            ", ".join(dependencies) if dependencies else "none declared"
        )
        if test_rows:
            test_table = (
                "| Test | Requirement | Test surface | Tier | Source acceptance "
                "assertion | Declared test command |\n"
                "| --- | --- | --- | --- | --- | --- |\n" + "\n".join(test_rows)
            )
        else:
            test_table = (
                "_MISSING SOURCE EVIDENCE: no test-coverage mapping was found "
                f"for {task_id}'s requirement(s)._"
            )
        source = task_sources.get(task_id)
        source_work = (
            "\n".join("> " + line if line.strip() else ">" for line in source.splitlines())
            if source else
            f"MISSING SOURCE EVIDENCE: no canonical TASKS.md declaration for {task_id}."
        )
        sections.append(
            f"### {task_id}\n\n"
            "- Requirement(s): "
            f"{clean_cell(', '.join(requirement_ids)) or 'MISSING SOURCE EVIDENCE: no requirement mapping for ' + task_id}\n"
            f"- Contributing plans: {clean_cell(', '.join(task_plans[task_id]))}\n"
            f"- Source-declared plan dependencies: {dependency_text}\n\n"
            f"#### {task_id} work and phase declaration\n\n"
            f"{source_work}\n\n"
            f"{test_table}\n\n"
            + "\n\n".join(
                f"#### {task_id} declared test command for {test_id}\n\n{command}"
                for test_id, command in sorted(command_blocks.items())
            )
            + "\n"
        )
    if not sections:
        sections.append(
            "_MISSING SOURCE EVIDENCE: no plan-to-task ordering was found in "
            "`checkpoints/plan-to-tasks.yaml`._\n"
        )
    return (
        frontmatter(evidence, "TDD.md")
        + f"# Test-Driven Development Plan: {evidence.title}\n\n"
        + supplement_provenance(evidence)
        + "## Document control and entry gate\n\n"
        f"- Feature: `{evidence.path.name}`.\n"
        f"- Source checkpoint date: `{evidence.generated_on}`.\n"
        "- Mode: source-bound test-plan projection for independent review.\n"
        "- Execution status: not established by generation; retain the "
        "canonical execution ledger and actual test artifacts.\n"
        "- Entry gate: reviewed requirement/acceptance scope, verified "
        "dependencies, named test scenarios and an approved runner. "
        "A missing source binding is not an approved default.\n\n"
        + "## Execution order and lifecycle\n\n"
        "Plans are displayed in dependency order and all contributing plan "
        "dependencies are retained. Unknown/external dependencies are not "
        "satisfied by this projection. The canonical task graph and source "
        "phase declarations govern intra-plan execution; listed task order "
        "does not invent missing task edges.\n\n"
        "### RED\n\n"
        "Execute the source-declared negative scenario before changing its "
        "behavior and retain the observed assertion failure, source/test "
        "revisions and command. For existing implementation, use a new "
        "specific regression or a verified pre-change revision; never remove "
        "working behavior to fabricate history. Setup failures are not RED.\n\n"
        "### GREEN\n\n"
        "Implement the canonical work package below and rerun its source "
        "acceptance scenarios and declared commands. Record actual outcomes "
        "separately from the source's completion claims.\n\n"
        "### REFACTOR\n\n"
        "Preserve the mapped acceptance, negative and regression assertions "
        "while removing duplication. Rerun the affected source test selection "
        "and retain results. Missing scenario/command bindings block an "
        "executable handoff and require source authoring, not a default command.\n\n"
        + source_sections(evidence.source_texts["TASKS.md"], ("dependency graph",))
        + "\n\n## Work packages\n\n" + "\n".join(sections)
        + "\n## Source test scenarios\n\n"
        + (source_table_rows(evidence.source_texts["TESTING.md"], set(test_meta), "TST-")
           or "MISSING SOURCE EVIDENCE: no named source test scenarios were found in TESTING.md.")
        + "\n\n## Canonical acceptance scenarios\n\n"
        + (source_table_rows(
            evidence.source_texts["SPECIFICATION.md"],
            {item.identifier for item in evidence.requirements},
            "AC-",
        ) or "Acceptance remains in the source declarations and mapped assertions above.")
        + "\n\n## Source-declared package commands\n\n"
        + (source_sections(evidence.source_texts["TESTING.md"], ("commands", "command groups"))
           or "No separate command section was found. Consult the canonical test scenarios; no command is invented here.")
        + "\n\n## Source failure, measurement and evidence guidance\n\n"
        + (source_sections(
            evidence.source_texts["TESTING.md"],
            ("failure", "negative control", "measurement", "evidence contract", "exit criteria"),
        ) or "MISSING SOURCE EVIDENCE: separate failure/measurement/evidence guidance was not found in TESTING.md.")
        + "\n\n## Evidence and exit gate\n\n"
        "Source execution claims remain in TASKS.md, TESTING.md and checkpoints. "
        "They are not independently verified by generating this file. "
        "An executable handoff needs complete scenario and command bindings; "
        "completion additionally requires retained phase logs, revisions, "
        "environment, timestamp, exit status, approval scope and measured "
        "acceptance where applicable. Preserve missing evidence as missing.\n\n"
        "## Review record\n\n"
        "This file creates no reviewer identity or approval. Bind any "
        "subsequent acceptance to its generated bytes and the source snapshot "
        "above; program authorization does not fabricate phase outcomes.\n\n"
        + document_checks(evidence)
    )


RENDERERS = {
    "CHECKLIST.md": render_checklist,
    "CROSS_ANALYSIS.md": render_cross_analysis,
    "VERIFICATION.md": render_verification,
    "SOURCE_TRACEABILITY.md": render_source_traceability,
}
SUPPLEMENT_RENDERERS = {
    "FRD.md": render_frd,
    "NFRD.md": render_nfrd,
    "TDD.md": render_tdd,
}


def packages(spec_root: pathlib.Path, selected: list[str]) -> list[pathlib.Path]:
    found = [
        path
        for path in sorted(spec_root.iterdir())
        if path.is_dir()
        and PACKAGE.match(path.name)
        and (path / "SPECIFICATION.md").is_file()
        and (path / "checkpoints").is_dir()
    ]
    if not selected:
        return found
    wanted = set(selected)
    matched = [
        path
        for path in found
        if path.name in wanted or path.name.split("-", 1)[0] in wanted
    ]
    missing = sorted(
        value
        for value in wanted
        if not any(
            path.name == value or path.name.split("-", 1)[0] == value
            for path in matched
        )
    )
    if missing:
        raise GenerationError(f"no checkpoint-backed package matched: {missing}")
    return matched


def managed(path: pathlib.Path) -> bool:
    return path.exists() and GENERATED_MARKER in path.read_text(encoding="utf-8")


def run(
    spec_root: pathlib.Path,
    selected: list[str],
    *,
    check: bool,
    force_generated: bool,
    include_supplements: bool = False,
) -> int:
    errors: list[str] = []
    changed: list[pathlib.Path] = []
    renderers = dict(RENDERERS)
    if include_supplements:
        renderers.update(SUPPLEMENT_RENDERERS)
    for package in packages(spec_root, selected):
        try:
            evidence = load_package(package)
            rendered = {
                artifact: renderer(evidence)
                for artifact, renderer in renderers.items()
                if not (
                    artifact in SUPPLEMENT_ARTIFACTS
                    and (package / artifact).exists()
                    and not managed(package / artifact)
                )
            }
            for artifact, expected in rendered.items():
                path = package / artifact
                if check:
                    if not path.exists():
                        errors.append(f"{path}: generated artifact is missing")
                    elif managed(path) and path.read_text(encoding="utf-8") != expected:
                        errors.append(f"{path}: generated artifact is stale")
                    continue
                if path.exists() and not (force_generated and managed(path)):
                    continue
                path.write_text(expected, encoding="utf-8")
                changed.append(path)
        except GenerationError as error:
            errors.append(str(error))
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    action = "validated" if check else "generated"
    print(
        f"SDD support artifacts {action}: "
        f"{len(packages(spec_root, selected))} package(s), "
        f"{len(changed)} file(s) changed"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--spec-root",
        type=pathlib.Path,
        default=DEFAULT_SPEC_ROOT,
        help="directory containing canonical numbered packages",
    )
    parser.add_argument(
        "--package",
        action="append",
        default=[],
        help="package directory name or three-digit feature ID; repeat as needed",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a generated artifact is missing or stale",
    )
    parser.add_argument(
        "--force-generated",
        action="store_true",
        help="refresh existing files only when they carry the generated marker",
    )
    parser.add_argument(
        "--include-supplements",
        action="store_true",
        help=(
            "additionally generate FRD.md, NFRD.md, and TDD.md as managed "
            "derived projections per package; hand-authored supplements "
            "(files without the generated marker) are never overwritten, "
            "even with --force-generated"
        ),
    )
    arguments = parser.parse_args(argv)
    spec_root = arguments.spec_root.resolve()
    if not spec_root.is_dir():
        print(f"ERROR: not a directory: {spec_root}", file=sys.stderr)
        return 2
    if arguments.check and arguments.force_generated:
        parser.error("--check and --force-generated cannot be combined")
    try:
        return run(
            spec_root,
            arguments.package,
            check=arguments.check,
            force_generated=arguments.force_generated,
            include_supplements=arguments.include_supplements,
        )
    except GenerationError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
